package ru.nelande.minelark.docgen;

import net.starlark.java.annot.Param;
import net.starlark.java.annot.StarlarkMethod;
import net.starlark.java.eval.StarlarkInt;
import ru.nelande.minelark.script.Log;
import ru.nelande.minelark.script.ModsApi;
import ru.nelande.minelark.script.Recipes;
import ru.nelande.minelark.script.RegistryApi;
import ru.nelande.minelark.script.StartupApi;

import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 * Generates the per-phase API reference under {@code docs/api/} directly from the
 * {@link StarlarkMethod} / {@link Param} annotations on the scripting API classes, so the docs are
 * always in lock-step with the code (single source of truth).
 *
 * <p>Usage: {@code DocGenerator <projectDir> [--check]}. With {@code --check} it writes nothing and
 * exits non-zero if any file is missing or out of date (used by the {@code checkApiDocs} task/CI).
 */
public final class DocGenerator {

    /** A documented scripting phase: page title, output file name, API class, and intro text. */
    private record Phase(String title, String fileName, Class<?> api, String namespace, String intro) {
    }

    private static final List<Phase> PHASES = List.of(
            new Phase(
                    "Common API Reference",
                    "common.md",
                    Log.class,
                    "log",
                    """
                    The `log` namespace is available to scripts in **every** phase. Use it to log
                    diagnostic messages; they appear in the game log / console tagged with the script
                    name and level.
                    """),
            new Phase(
                    "Startup API Reference",
                    "startup.md",
                    StartupApi.class,
                    "",
                    """
                    Functions available to scripts in the **`minelark/startup/`** folder. Startup \
                    scripts run once at launch, before the game freezes its registries, which is \
                    why this is where content is registered.

                    All content is registered under the **`minelark:`** namespace.
                    """),
            new Phase(
                    "Server API Reference",
                    "server.md",
                    Recipes.class,
                    "recipes",
                    """
                    The **`recipes`** namespace, available to scripts in the **`minelark/server/`** \
                    folder. Recipes are reloadable data - re-apply them in-game with `/minelark \
                    reload`. Ids and tags without a namespace default to `minecraft:`; prefix a tag \
                    with `#`.

                    Server scripts also react to [events](events.md), send styled [text](text.md), \
                    and register their own [commands](commands.md).
                    """),
            new Phase(
                    "Mods API Reference",
                    "mods.md",
                    ModsApi.class,
                    "mods",
                    """
                    The **`mods`** namespace, available to **server** and **client** scripts. Use it to \
                    check what else is installed so a pack can adapt to its environment - for example, \
                    only add a recipe when the mod it depends on is present:

                    ```python
                    if mods.loaded("create"):
                        recipes.shapeless("create:cogwheel", ["minelark:ruby"])
                    ```
                    """),
            new Phase(
                    "Registry API Reference",
                    "registry.md",
                    RegistryApi.class,
                    "registry",
                    """
                    The **`registry`** namespace, available to **server** and **client** scripts. Query \
                    the game registries to see whether an item/block/entity/fluid exists and to list the \
                    ids other mods registered. Ids without a namespace default to `minecraft:`.

                    This is read-only discovery - a sandbox-preserving window onto the game's content, \
                    with no reflection into other mods.
                    """)
            // Note: the `events` API (docs/api/events.md) is hand-written - its nested
            // `events.<namespace>.<EVENT>` shape doesn't fit this flat generator.
    );

    private static final String GENERATED_NOTICE =
            "<!-- Generated by `./gradlew generateApiDocs` from @StarlarkMethod annotations. Do not edit by hand. -->";

    public static void main(String[] args) throws IOException {
        if (args.length == 0) {
            System.err.println("usage: DocGenerator <projectDir> [--check]");
            System.exit(2);
            return;
        }
        Path projectDir = Path.of(args[0]);
        boolean check = args.length > 1 && "--check".equals(args[1]);
        Path apiDir = projectDir.resolve("docs").resolve("api");

        List<String> stale = new ArrayList<>();
        if (!check) {
            Files.createDirectories(apiDir);
        }

        for (Phase phase : PHASES) {
            String expected = render(phase);
            Path file = apiDir.resolve(phase.fileName());
            if (check) {
                String actual = Files.exists(file) ? Files.readString(file) : "";
                if (!expected.equals(actual)) {
                    stale.add("docs/api/" + phase.fileName());
                }
            } else {
                Files.writeString(file, expected);
                System.out.println("Generated docs/api/" + phase.fileName());
            }
        }

        if (check && !stale.isEmpty()) {
            System.err.println("API docs are out of date: " + String.join(", ", stale));
            System.err.println("Run `./gradlew generateApiDocs` and commit the result.");
            System.exit(1);
        }
    }

    private static String render(Phase phase) {
        StringBuilder sb = new StringBuilder();
        sb.append(GENERATED_NOTICE).append("\n\n");
        sb.append("# ").append(phase.title()).append("\n\n");
        sb.append(phase.intro().strip()).append("\n\n");

        List<Method> builtins = Arrays.stream(phase.api().getDeclaredMethods())
                .filter(m -> m.isAnnotationPresent(StarlarkMethod.class))
                .sorted(Comparator.comparing(m -> m.getAnnotation(StarlarkMethod.class).name()))
                .toList();

        for (Method m : builtins) {
            sb.append("---\n\n");
            renderMethod(sb, m, phase.namespace());
        }

        sb.append("---\n\n");
        sb.append("*The usual Starlark builtins (`print`, `len`, `range`, and so on) work here too. "
                + "See [The Starlark Language](../language.md).*\n");
        return sb.toString();
    }

    private static void renderMethod(StringBuilder sb, Method m, String namespace) {
        StarlarkMethod sm = m.getAnnotation(StarlarkMethod.class);
        Param[] params = sm.parameters();
        Class<?>[] types = m.getParameterTypes();

        // Signature, e.g.  item(id, max_stack_size = 64)  or  log.info(message)
        String qualifiedName = namespace.isEmpty() ? sm.name() : namespace + "." + sm.name();
        sb.append("## `").append(qualifiedName).append('(');
        for (int i = 0; i < params.length; i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(params[i].name());
            if (!params[i].defaultValue().isEmpty()) {
                sb.append(" = ").append(params[i].defaultValue());
            }
        }
        sb.append(")`\n\n");

        if (!sm.doc().isEmpty()) {
            sb.append(sm.doc().strip()).append("\n\n");
        }

        if (params.length > 0) {
            sb.append("**Parameters**\n\n");
            sb.append("| Name | Type | Required | Default | Description |\n");
            sb.append("|---|---|---|---|---|\n");
            for (int i = 0; i < params.length; i++) {
                Param p = params[i];
                boolean required = p.defaultValue().isEmpty();
                String type = i < types.length ? starlarkType(types[i]) : "";
                String doc = p.doc().isEmpty() ? "" : p.doc().strip().replace("\n", " ");
                sb.append("| `").append(p.name()).append("` | ")
                        .append(type).append(" | ")
                        .append(required ? "yes" : "no").append(" | ")
                        .append(required ? "-" : "`" + p.defaultValue() + "`").append(" | ")
                        .append(doc).append(" |\n");
            }
            sb.append('\n');
        }
    }

    private static String starlarkType(Class<?> type) {
        if (type == String.class) {
            return "string";
        }
        if (type == StarlarkInt.class || type == int.class || type == Integer.class) {
            return "int";
        }
        if (type == boolean.class || type == Boolean.class) {
            return "bool";
        }
        if (type == Object.class) {
            // Params typed Object accept a few Starlark types (e.g. an int or float, or an id
            // string or handle); the per-parameter description says which.
            return "any";
        }
        return type.getSimpleName().toLowerCase();
    }

    private DocGenerator() {
    }
}
